# 使用官方Python 3.11基础镜像
FROM python:3.11
 
# 设置环境变量，可以省略
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
 
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# 复制当前目录下的文件到容器内的/app目录
COPY . /app
 
# 工作目录设置为/app
WORKDIR /app
 
# 可选：运行任何安装命令，例如python setup.py install